function E = equationmap(y)
% This function is used to check if the equations are all satisfied
global  r kappa  a ps kappap kappav  kappas
syms zita1 zita2 thetaf1 thetaf2 rho  k delta
psi =sym("psi");
ks=sym("ks");
kp=sym("kp");
kv=sym("kv");
alpha=sym("alpha");

%% dksi1/dt
ksi1dot=sin(thetaf1)+(1/24).*exp(1).^((sqrt(-1)*(-1)).*thetaf2).*pi.^2.*rho.^2.*(( ...
  sqrt(-1)*(-3)).*psi.*(csch((1/2).*pi.*(delta+sqrt(-1).*(zita1+(-1).*zita2))) ...
  .^2+sech((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(zita1+zita2))).^2)+(sqrt(-1)*3) ...
  .*exp(1).^((sqrt(-1)*2).*thetaf2).*psi.*(csch((1/2).*pi.*(delta+(sqrt(-1)*( ...
  -1)).*(zita1+(-1).*zita2))).^2+sech((1/2).*pi.*(delta+sqrt(-1).*(zita1+zita2))) ...
  .^2)+(-2).*exp(1).^(sqrt(-1).*thetaf2).*((-1)+3.*sec(pi.*zita1).^2).*sin( ...
  thetaf1));
%% dksi2/dt
ksi2dot=(sqrt(-1)*(-1/8)).*exp(1).^((sqrt(-1)*(-1)).*thetaf1).*pi.^2.*rho.^2.*( csch((1/2).*pi.*...
    (delta+sqrt(-1).*(zita1+(-1).*zita2))).^2+(-1).*exp(1).^(( ...
  sqrt(-1)*2).*thetaf1).*(csch((1/2).*pi.*(delta+(sqrt(-...
1)*(-1)).*zita1+sqrt( ...
  -1).*zita2)).^2+sech((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*...
(zita1+zita2))).^2)+ ...
  sech((1/2).*pi.*(delta+sqrt(-1).*(zita1+zita2))).^2)+...
  (1/12).*psi.*(12+pi.^2.* ...
  rho.^2+(-3).*pi.^2.*rho.^2.*sec(pi.*zita2).^2).*sin(thetaf2);
%% lambdadot

lambdadot=(1/24).*(96.*alpha.*zita1.^2+(-96).*alpha.*zita2.^2+(-24).*cos(thetaf1)+2.*pi.^2.* ...
  rho.^2.*cos(thetaf1)+24.*psi.*cos(thetaf2)+(-2).*pi.^2.*rho.^2.*psi.*cos(thetaf2)+6.* ...
  pi.^2.*rho.^2.*cos(thetaf1).*sec(pi.*zita1).^2+(-6).*pi.^2.*rho.^2.*psi.*cos( ...
  thetaf2).*sec(pi.*zita2).^2+(-3).*pi.^2.*rho.^2.*cos(thetaf1).*sech((1/2).*pi.* ...
  (delta+(sqrt(-1)*(-1)).*(zita1+zita2))).^2+3.*pi.^2.*rho.^2.*psi.*cos(thetaf2).* ...
  sech((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(zita1+zita2))).^2+(-3).*pi.^2.* ...
  rho.^2.*cos(thetaf1).*sech((1/2).*pi.*(delta+sqrt(-1).*(zita1+zita2))).^2+3.* ...
  pi.^2.*rho.^2.*psi.*cos(thetaf2).*sech((1/2).*pi.*(delta+sqrt(-1).*(zita1+zita2))) ...
  .^2+(sqrt(-1)*(-3)).*pi.^2.*rho.^2.*sech((1/2).*pi.*(delta+(sqrt(-1)*( ...
  -1)).*(zita1+zita2))).^2.*sin(thetaf1)+(sqrt(-1)*3).*pi.^2.*rho.^2.*sech((1/2) ...
  .*pi.*(delta+sqrt(-1).*(zita1+zita2))).^2.*sin(thetaf1)+(sqrt(-1)*(-3)).*pi.^2.* ...
  rho.^2.*psi.*sech((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(zita1+zita2))).^2.*sin( ...
  thetaf2)+(sqrt(-1)*3).*pi.^2.*rho.^2.*psi.*sech((1/2).*pi.*(delta+sqrt(-1).*( ...
  zita1+zita2))).^2.*sin(thetaf2)+3.*pi.^2.*rho.^2.*csch((1/2).*pi.*(delta+sqrt(-1) ...
  .*(zita1+(-1).*zita2))).^2.*(cos(thetaf1)+(-1).*psi.*cos(thetaf2)+(sqrt(-1)*(-1)) ...
  .*(sin(thetaf1)+(-1).*psi.*sin(thetaf2)))+3.*pi.^2.*rho.^2.*csch((1/2).*pi.*( ...
  delta+(sqrt(-1)*(-1)).*(zita1+(-1).*zita2))).^2.*(cos(thetaf1)+(-1).*psi.*cos(thetaf2) ...
  +sqrt(-1).*(sin(thetaf1)+(-1).*psi.*sin(thetaf2))));
%% T-DIPOLE

%thetaf2dot
theta1dot=(1/8).*exp(1).^((sqrt(-1)*(-1)).*(thetaf1+thetaf2)).*(64.*exp(1).^(sqrt( ...
  -1).*(thetaf1+thetaf2)).*alpha.*k.*zita1+64.*exp(1).^(sqrt(-1).*(thetaf1+thetaf2)).*alpha.* ...
  zita1.*cos(thetaf1).^2+(sqrt(-1)*(-1)).*exp(1).^((sqrt(-1)*3).*thetaf1+(sqrt( ...
  -1)*2).*thetaf2).*pi.^3.*rho.^2.*psi.*coth((1/2).*pi.*(delta+(sqrt(-1)*(-1)).* ...
  (zita1+(-1).*zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(zita1+(-1).*zita2) ...
  )).^2+sqrt(-1).*exp(1).^((sqrt(-1)*(-1)).*thetaf1).*pi.^3.*rho.^2.*psi.* ...
  coth((1/2).*pi.*(delta+sqrt(-1).*(zita1+(-1).*zita2))).*csch((1/2).*pi.*(delta+ ...
  sqrt(-1).*(zita1+(-1).*zita2))).^2+(sqrt(-1)*(-1)).*exp(1).^(sqrt(-1).* ...
  thetaf1).*pi.^3.*rho.^2.*psi.*cos(thetaf1).^2.*coth((1/2).*pi.*(delta+(sqrt(-1)*( ...
  -1)).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))) ...
  .^2+sqrt(-1).*exp(1).^(sqrt(-1).*(thetaf1+2.*thetaf2)).*pi.^3.*rho.^2.*psi.* ...
  cos(thetaf1).^2.*coth((1/2).*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).*csch((1/2) ...
  .*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).^2+sqrt(-1).*exp(1).^(sqrt(-1).* ...
  thetaf1).*pi.^3.*rho.^2.*psi.*coth((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+ ...
  zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).^2.*sin( ...
  thetaf1).^2+(sqrt(-1)*(-1)).*exp(1).^(sqrt(-1).*(thetaf1+2.*thetaf2)).*pi.^3.* ...
  rho.^2.*psi.*coth((1/2).*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).*csch((1/2).* ...
  pi.*(delta+sqrt(-1).*(1+zita1+zita2))).^2.*sin(thetaf1).^2+exp(1).^(sqrt(-1).* ...
  thetaf1).*pi.^3.*rho.^2.*psi.*coth((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+ ...
  zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).^2.*sin(2.* ...
  thetaf1)+exp(1).^(sqrt(-1).*(thetaf1+2.*thetaf2)).*pi.^3.*rho.^2.*psi.*coth((1/2) ...
  .*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+sqrt(-1).*(1+ ...
  zita1+zita2))).^2.*sin(2.*thetaf1)+(1/2).*exp(1).^(sqrt(-1).*thetaf2).*pi.^3.* ...
  rho.^2.*sec(pi.*zita1).^2.*tan(pi.*zita1)+(-1/2).*exp(1).^(sqrt(-1).*(4.* ...
 thetaf1+thetaf2)).*pi.^3.*rho.^2.*sec(pi.*zita1).^2.*tan(pi.*zita1)+exp(1).^(sqrt( ...
  -1).*thetaf2).*pi.^3.*rho.^2.*cos(thetaf1).^2.*sec(pi.*zita1).^2.*tan(pi.*zita1)+ ...
  exp(1).^(sqrt(-1).*(2.*thetaf1+thetaf2)).*pi.^3.*rho.^2.*cos(thetaf1).^2.*sec( ...
  pi.*zita1).^2.*tan(pi.*zita1)+(sqrt(-1)*2).*exp(1).^(sqrt(-1).*thetaf2).* ...
  pi.^3.*rho.^2.*cos(thetaf1).*sec(pi.*zita1).^2.*sin(thetaf1).*tan(pi.*zita1)+(-1) ...
  .*exp(1).^(sqrt(-1).*thetaf2).*pi.^3.*rho.^2.*sec(pi.*zita1).^2.*sin(thetaf1) ...
  .^2.*tan(pi.*zita1)+(-1).*exp(1).^(sqrt(-1).*(2.*thetaf1+thetaf2)).*pi.^3.* ...
  rho.^2.*sec(pi.*zita1).^2.*sin(thetaf1).^2.*tan(pi.*zita1))+ks*sin(thetaf1)+(1+(-1).*cos(thetaf2+atan(delta.^(-1).*(zita1+(-1).*zita2)))).*(kv.*psi.*sin(thetaf1+( ...
  -1).*thetaf2)+kp.*(delta.^2+(zita1+(-1).*zita2).^2).^(1/2).*sin(thetaf2+atan(delta.^(-1) ...
  .*(zita1+(-1).*zita2))));

% thetaf2dot

theta2dot=(1/8).*exp(1).^((sqrt(-1)*(-1)).*(thetaf1+thetaf2)).*(64.*exp(1).^(sqrt( ...
  -1).*(thetaf1+thetaf2)).*alpha.*k.*zita2+64.*exp(1).^(sqrt(-1).*(thetaf1+thetaf2)).*alpha.* ...
  zita2.*cos(thetaf2).^2+sqrt(-1).*exp(1).^((sqrt(-1)*2).*thetaf1+(sqrt(-1)*3) ...
  .*thetaf2).*pi.^3.*rho.^2.*coth((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(zita1+(-1) ...
  .*zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(zita1+(-1).*zita2))).^2+( ...
  sqrt(-1)*(-1)).*exp(1).^((sqrt(-1)*(-1)).*thetaf2).*pi.^3.*rho.^2.*coth( ...
  (1/2).*pi.*(delta+sqrt(-1).*(zita1+(-1).*zita2))).*csch((1/2).*pi.*(delta+sqrt( ...
  -1).*(zita1+(-1).*zita2))).^2+(sqrt(-1)*(-1)).*exp(1).^(sqrt(-1).*(2.* ...
  thetaf1+thetaf2)).*pi.^3.*rho.^2.*cos(thetaf2).^2.*coth((1/2).*pi.*(delta+(sqrt(-1)* ...
  (-1)).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2)) ...
  ).^2+sqrt(-1).*exp(1).^(sqrt(-1).*thetaf2).*pi.^3.*rho.^2.*cos(thetaf2).^2.* ...
  coth((1/2).*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+sqrt( ...
  -1).*(1+zita1+zita2))).^2+(-2).*exp(1).^(sqrt(-1).*(2.*thetaf1+thetaf2)).* ...
  pi.^3.*rho.^2.*cos(thetaf2).*coth((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+ ...
  zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).^2.*sin( ...
  thetaf2)+(-2).*exp(1).^(sqrt(-1).*thetaf2).*pi.^3.*rho.^2.*cos(thetaf2).*coth(( ...
  1/2).*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+sqrt(-1).*( ...
  1+zita1+zita2))).^2.*sin(thetaf2)+sqrt(-1).*exp(1).^(sqrt(-1).*(2.*thetaf1+thetaf2)) ...
  .*pi.^3.*rho.^2.*coth((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).* ...
  csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).^2.*sin(thetaf2).^2+( ...
  sqrt(-1)*(-1)).*exp(1).^(sqrt(-1).*thetaf2).*pi.^3.*rho.^2.*coth((1/2).* ...
  pi.*(delta+sqrt(-1).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+sqrt(-1).*(1+zita1+ ...
  zita2))).^2.*sin(thetaf2).^2+(1/2).*exp(1).^(sqrt(-1).*thetaf1).*pi.^3.* ...
  rho.^2.*psi.*sec(pi.*zita2).^2.*tan(pi.*zita2)+(-1/2).*exp(1).^(sqrt(-1).*( ...
  thetaf1+4.*thetaf2)).*pi.^3.*rho.^2.*psi.*sec(pi.*zita2).^2.*tan(pi.*zita2)+exp(1) ...
  .^(sqrt(-1).*thetaf1).*pi.^3.*rho.^2.*psi.*cos(thetaf2).^2.*sec(pi.*zita2).^2.* ...
  tan(pi.*zita2)+exp(1).^(sqrt(-1).*(thetaf1+2.*thetaf2)).*pi.^3.*rho.^2.*psi.*cos( ...
  thetaf2).^2.*sec(pi.*zita2).^2.*tan(pi.*zita2)+(sqrt(-1)*2).*exp(1).^(sqrt( ...
  -1).*thetaf1).*pi.^3.*rho.^2.*psi.*cos(thetaf2).*sec(pi.*zita2).^2.*sin(thetaf2).* ...
  tan(pi.*zita2)+(-1).*exp(1).^(sqrt(-1).*thetaf1).*pi.^3.*rho.^2.*psi.*sec( ...
  pi.*zita2).^2.*sin(thetaf2).^2.*tan(pi.*zita2)+(-1).*exp(1).^(sqrt(-1).*( ...
  thetaf1+2.*thetaf2)).*pi.^3.*rho.^2.*psi.*sec(pi.*zita2).^2.*sin(thetaf2).^2.*tan( ...
  pi.*zita2))+ks*psi*sin(thetaf2)+(1+(-1).*cos(thetaf2+atan(delta.^(-1).*(zita1+(-1).*zita2)))).*(kv.*psi.*sin(thetaf1+( ...
  -1).*thetaf2)+kp.*(delta.^2+(zita1+(-1).*zita2).^2).^(1/2).*sin(thetaf2+atan(delta.^(-1) ...
  .*(zita1+(-1).*zita2))));


%% A-dipole with walls
% theta1dot=(1/16).*exp(1).^((sqrt(-1)*(-1)).*(2.*thetaf1+thetaf2)).*(128.*exp(1).^( ...
%   sqrt(-1).*(2.*thetaf1+thetaf2)).*alpha.*k.*zita1+(sqrt(-1)*2).*exp(1).^((sqrt(-1) ...
%   *2).*(2.*thetaf1+thetaf2)).*pi.^3.*rho.^2.*psi.*coth((1/2).*pi.*(delta+(sqrt(-1)*( ...
%   -1)).*(zita1+(-1).*zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(zita1+( ...
%   -1).*zita2))).^2+(sqrt(-1)*(-2)).*pi.^3.*rho.^2.*psi.*coth((1/2).*pi.*(delta+ ...
%   sqrt(-1).*(zita1+(-1).*zita2))).*csch((1/2).*pi.*(delta+sqrt(-1).*(zita1+(-1).* ...
%   zita2))).^2+sqrt(-1).*((-1)+exp(1).^((sqrt(-1)*4).*thetaf1)).*pi.^3.* ...
%   rho.^2.*psi.*coth((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).*csch(( ...
%   1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).^2+(sqrt(-1)*2).*exp(1) ...
%   .^((sqrt(-1)*2).*thetaf1).*pi.^3.*rho.^2.*psi.*cos(thetaf1).^2.*coth((1/2).* ...
%   pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)* ...
%   (-1)).*(1+zita1+zita2))).^2+(sqrt(-1)*(-2)).*exp(1).^((sqrt(-1)*2).*( ...
%   thetaf1+thetaf2)).*pi.^3.*rho.^2.*psi.*cos(thetaf1).^2.*coth((1/2).*pi.*(delta+sqrt( ...
%   -1).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).^2+ ...
%   128.*exp(1).^(sqrt(-1).*(2.*thetaf1+thetaf2)).*alpha.*zita1.*sin(thetaf1).^2+( ...
%   sqrt(-1)*(-2)).*exp(1).^((sqrt(-1)*2).*thetaf1).*pi.^3.*rho.^2.*psi.*coth( ...
%   (1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+( ...
%   sqrt(-1)*(-1)).*(1+zita1+zita2))).^2.*sin(thetaf1).^2+(sqrt(-1)*2).*exp(1) ...
%   .^((sqrt(-1)*2).*(thetaf1+thetaf2)).*pi.^3.*rho.^2.*psi.*coth((1/2).*pi.*(delta+ ...
%   sqrt(-1).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+sqrt(-1).*(1+zita1+zita2))) ...
%   .^2.*sin(thetaf1).^2+(-2).*exp(1).^((sqrt(-1)*2).*(thetaf1+thetaf2)).*pi.^3.* ...
%   rho.^2.*psi.*coth((1/2).*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).*csch((1/2).* ...
%   pi.*(delta+sqrt(-1).*(1+zita1+zita2))).^2.*sin(2.*thetaf1)+(-1).*exp(1).^(sqrt( ...
%   -1).*(thetaf1+thetaf2)).*pi.^3.*rho.^2.*sec(pi.*zita1).^2.*tan(pi.*zita1)+exp(1) ...
%   .^(sqrt(-1).*(5.*thetaf1+thetaf2)).*pi.^3.*rho.^2.*sec(pi.*zita1).^2.*tan(pi.* ...
%   zita1)+(-2).*exp(1).^(sqrt(-1).*(thetaf1+thetaf2)).*pi.^3.*rho.^2.*cos(thetaf1) ...
%   .^2.*sec(pi.*zita1).^2.*tan(pi.*zita1)+(-2).*exp(1).^(sqrt(-1).*(3.*thetaf1+ ...
%   thetaf2)).*pi.^3.*rho.^2.*cos(thetaf1).^2.*sec(pi.*zita1).^2.*tan(pi.*zita1)+( ...
%   sqrt(-1)*(-4)).*exp(1).^(sqrt(-1).*(thetaf1+thetaf2)).*pi.^3.*rho.^2.*cos( ...
%   thetaf1).*sec(pi.*zita1).^2.*sin(thetaf1).*tan(pi.*zita1)+2.*exp(1).^(sqrt(-1).* ...
%   (thetaf1+thetaf2)).*pi.^3.*rho.^2.*sec(pi.*zita1).^2.*sin(thetaf1).^2.*tan(pi.*zita1)+ ...
%   2.*exp(1).^(sqrt(-1).*(3.*thetaf1+thetaf2)).*pi.^3.*rho.^2.*sec(pi.*zita1).^2.* ...
%   sin(thetaf1).^2.*tan(pi.*zita1))+ks*sin(thetaf1)+((-1)+(-1).*cos(thetaf1+atan(delta.^(-1).*(zita1+(-1).*zita2)))).*(kv.*sin(thetaf1+( ...
%   -1).*thetaf2)+kp.*(delta.^2+(zita1+(-1).*zita2).^2).^(1/2).*sin(thetaf1+atan(delta.^(-1) ...
%   .*(zita1+(-1).*zita2))));
% 
% theta2dot=(1/8).*exp(1).^((sqrt(-1)*(-1)).*(thetaf1+thetaf2)).*(64.*exp(1).^(sqrt( ...
%   -1).*(thetaf1+thetaf2)).*alpha.*k.*zita2+(sqrt(-1)*(-1)).*exp(1).^((sqrt(-1)*2).* ...
%   thetaf1+(sqrt(-1)*3).*thetaf2).*pi.^3.*rho.^2.*coth((1/2).*pi.*(delta+(sqrt(-1)* ...
%   (-1)).*(zita1+(-1).*zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(zita1+( ...
%   -1).*zita2))).^2+sqrt(-1).*exp(1).^((sqrt(-1)*(-1)).*thetaf2).*pi.^3.* ...
%   rho.^2.*coth((1/2).*pi.*(delta+sqrt(-1).*(zita1+(-1).*zita2))).*csch((1/2).* ...
%   pi.*(delta+sqrt(-1).*(zita1+(-1).*zita2))).^2+sqrt(-1).*exp(1).^(sqrt(-1).*( ...
%   2.*thetaf1+thetaf2)).*pi.^3.*rho.^2.*cos(thetaf2).^2.*coth((1/2).*pi.*(delta+(sqrt( ...
%   -1)*(-1)).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+ ...
%   zita2))).^2+(sqrt(-1)*(-1)).*exp(1).^(sqrt(-1).*thetaf2).*pi.^3.*rho.^2.* ...
%   cos(thetaf2).^2.*coth((1/2).*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).*csch((1/2) ...
%   .*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).^2+64.*exp(1).^(sqrt(-1).*(thetaf1+thetaf2) ...
%   ).*zita2.*alpha.*sin(thetaf2).^2+(sqrt(-1)*(-1)).*exp(1).^(sqrt(-1).*(2.* ...
%   thetaf1+thetaf2)).*pi.^3.*rho.^2.*coth((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+ ...
%   zita2))).*csch((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).^2.*sin( ...
%   thetaf2).^2+sqrt(-1).*exp(1).^(sqrt(-1).*thetaf2).*pi.^3.*rho.^2.*coth((1/2) ...
%   .*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).*csch((1/2).*pi.*(delta+sqrt(-1).*(1+ ...
%   zita1+zita2))).^2.*sin(thetaf2).^2+exp(1).^(sqrt(-1).*(2.*thetaf1+thetaf2)).*pi.^3.* ...
%   rho.^2.*coth((1/2).*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).*csch((1/2) ...
%   .*pi.*(delta+(sqrt(-1)*(-1)).*(1+zita1+zita2))).^2.*sin(2.*thetaf2)+exp(1).^( ...
%   sqrt(-1).*thetaf2).*pi.^3.*rho.^2.*coth((1/2).*pi.*(delta+sqrt(-1).*(1+zita1+ ...
%   zita2))).*csch((1/2).*pi.*(delta+sqrt(-1).*(1+zita1+zita2))).^2.*sin(2.*thetaf2)+( ...
%   -1/2).*exp(1).^(sqrt(-1).*thetaf1).*pi.^3.*rho.^2.*psi.*sec(pi.*zita2).^2.* ...
%   tan(pi.*zita2)+(1/2).*exp(1).^(sqrt(-1).*(thetaf1+4.*thetaf2)).*pi.^3.*rho.^2.* ...
%   psi.*sec(pi.*zita2).^2.*tan(pi.*zita2)+(-1).*exp(1).^(sqrt(-1).*thetaf1).* ...
%   pi.^3.*rho.^2.*psi.*cos(thetaf2).^2.*sec(pi.*zita2).^2.*tan(pi.*zita2)+(-1).* ...
%   exp(1).^(sqrt(-1).*(thetaf1+2.*thetaf2)).*pi.^3.*rho.^2.*psi.*cos(thetaf2).^2.* ...
%   sec(pi.*zita2).^2.*tan(pi.*zita2)+(sqrt(-1)*(-2)).*exp(1).^(sqrt(-1).* ...
%   thetaf1).*pi.^3.*rho.^2.*psi.*cos(thetaf2).*sec(pi.*zita2).^2.*sin(thetaf2).*tan(pi.* ...
%   zita2)+exp(1).^(sqrt(-1).*thetaf1).*pi.^3.*rho.^2.*psi.*sec(pi.*zita2).^2.*sin( ...
%   thetaf2).^2.*tan(pi.*zita2)+exp(1).^(sqrt(-1).*(thetaf1+2.*thetaf2)).*pi.^3.* ...
%   rho.^2.*psi.*sec(pi.*zita2).^2.*sin(thetaf2).^2.*tan(pi.*zita2))+ks*psi*sin(thetaf2)+(1+(-1).*cos(thetaf2+atan(delta.^(-1).*(zita1+(-1).*zita2)))).*(kv.*psi.*sin(thetaf1+( ...
%   -1).*thetaf2)+kp.*(delta.^2+(zita1+(-1).*zita2).^2).^(1/2).*sin(thetaf2+atan(delta.^(-1) ...
%   .*(zita1+(-1).*zita2))));

ksi1eq=double(subs(ksi1dot,[rho,k,alpha,psi,zita1,zita2,delta,thetaf1,thetaf2,ks,kp,kv], [r,kappa,a,ps,y(1),y(2),y(3),y(4),y(5),kappas,kappap,kappav]));
ksi2eq=double(subs(ksi2dot,[rho,k,alpha,psi,zita1,zita2,delta,thetaf1,thetaf2,ks,kp,kv], [r,kappa,a,ps,y(1),y(2),y(3),y(4),y(5),kappas,kappap,kappav]));
lambdaeq=double(subs(lambdadot,[rho,k,alpha,psi,zita1,zita2,delta,thetaf1,thetaf2,ks,kp,kv], [r,kappa,a,ps,y(1),y(2),y(3),y(4),y(5),kappas,kappap,kappav]));
theta1eq=double(subs(theta1dot,[rho,k,alpha,psi,zita1,zita2,delta,thetaf1,thetaf2,ks,kp,kv], [r,kappa,a,ps,y(1),y(2),y(3),y(4),y(5),kappas,kappap,kappav]));
theta2eq=double(subs(theta2dot,[rho,k,alpha,psi,zita1,zita2,delta,thetaf1,thetaf2,ks,kp,kv], [r,kappa,a,ps,y(1),y(2),y(3),y(4),y(5),kappas,kappap,kappav]));

tol=10^-05; %tolerance can be set

if abs(ksi1eq)<=tol && abs(ksi2eq)<=tol && abs(lambdaeq)<=tol && abs(theta1eq)<=tol && abs(theta2eq)<=tol
    E=1;
else 
    E=0;
end

end